const data = [
  {
    esg_id: 4720,
    company_name: 'Microsoft Corporation',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'MSFT',
    environment_grade: 'A',
    environment_level: 'High',
    social_grade: 'BBB',
    social_level: 'High',
    governance_grade: 'BB',
    governance_level: 'Medium',
    total_grade: 'A',
    total_level: 'High',
    disclaimer:
      'ESG Enterprise\'s ESG Rating data ("Scores") are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '13-03-2022',
    environment_score: 510,
    social_score: 414,
    governance_score: 375,
    total: 1299,
  },
  {
    esg_id: 8742,
    company_name: 'Lindian Resources Limited',
    exchange_symbol: 'ASX',
    stock_symbol: 'LIN',
    environment_grade: 'CC',
    environment_level: 'Low',
    social_grade: 'B',
    social_level: 'Medium',
    governance_grade: 'CCC',
    governance_level: 'Low',
    total_grade: 'CCC',
    total_level: 'Low',
    disclaimer:
      'ESG Enterprise\'s ESG Rating data ("Scores") are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '15-03-2022',
    environment_score: 110,
    social_score: 240,
    governance_score: 175,
    total: 525,
  },
  {
    esg_id: 75,
    company_name: 'Accenture plc',
    exchange_symbol: 'NYSE',
    stock_symbol: 'ACN',
    environment_grade: 'A',
    environment_level: 'High',
    social_grade: 'BB',
    social_level: 'Medium',
    governance_grade: 'BB',
    governance_level: 'Medium',
    total_grade: 'A',
    total_level: 'High',
    disclaimer:
      'ESG Enterprise\'s ESG Rating data ("Scores") are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '11-03-2022',
    environment_score: 575,
    social_score: 396,
    governance_score: 360,
    total: 1331,
  },
  {
    esg_id: 3950,
    company_name: 'J.B. Hunt Transport Services, Inc.',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'JBHT',
    environment_grade: 'A',
    environment_level: 'High',
    social_grade: 'BB',
    social_level: 'Medium',
    governance_grade: 'BB',
    governance_level: 'Medium',
    total_grade: 'A',
    total_level: 'High',
    disclaimer:
      'ESG Enterprise\'s ESG Rating data ("Scores") are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '13-03-2022',
    environment_score: 550,
    social_score: 355,
    governance_score: 305,
    total: 1210,
  },
  {
    esg_id: 7853,
    company_name: 'Xylem Inc.',
    exchange_symbol: 'NYSE',
    stock_symbol: 'XYL',
    environment_grade: 'BB',
    environment_level: 'Medium',
    social_grade: 'B',
    social_level: 'Medium',
    governance_grade: 'B',
    governance_level: 'Medium',
    total_grade: 'BB',
    total_level: 'Medium',
    disclaimer:
      'ESG Enterprise\'s ESG Rating data ("Scores") are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '15-03-2022',
    environment_score: 389,
    social_score: 253,
    governance_score: 210,
    total: 852,
  },
  {
    esg_id: 7020,
    company_name: 'Texas Instruments Incorporated',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'TXN',
    environment_grade: 'A',
    environment_level: 'High',
    social_grade: 'BB',
    social_level: 'Medium',
    governance_grade: 'BB',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'High',
    disclaimer:
      'ESG Enterprise\'s ESG Rating data ("Scores") are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '15-03-2022',
    environment_score: 500,
    social_score: 300,
    governance_score: 300,
    total: 1100,
  },
  {
    esg_id: 6241,
    company_name: 'salesforce.com, inc.',
    exchange_symbol: 'NYSE',
    stock_symbol: 'CRM',
    environment_grade: 'B',
    environment_level: 'Medium',
    social_grade: 'B',
    social_level: 'Medium',
    governance_grade: 'B',
    governance_level: 'Medium',
    total_grade: 'B',
    total_level: 'Medium',
    disclaimer:
      'ESG Enterprise\'s ESG Rating data ("Scores") are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '14-03-2022',
    environment_score: 255,
    social_score: 222,
    governance_score: 240,
    total: 717,
  },
  {
    esg_id: 3091,
    company_name: 'Gildan Activewear Inc.',
    exchange_symbol: 'NYSE',
    stock_symbol: 'GIL',
    environment_grade: 'A',
    environment_level: 'High',
    social_grade: 'B',
    social_level: 'Medium',
    governance_grade: 'B',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'High',
    disclaimer:
      'ESG Enterprise\'s ESG Rating data ("Scores") are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '12-03-2022',
    environment_score: 555,
    social_score: 202,
    governance_score: 260,
    total: 1017,
  },
  {
    esg_id: 10059,
    company_name: 'McBride plc',
    exchange_symbol: 'LON',
    stock_symbol: 'MCB',
    environment_grade: 'A',
    environment_level: 'High',
    social_grade: 'BB',
    social_level: 'Medium',
    governance_grade: 'BB',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'High',
    disclaimer:
      'ESG Enterprise\'s ESG Rating data ("Scores") are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '16-03-2022',
    environment_score: 500,
    social_score: 300,
    governance_score: 300,
    total: 1100,
  },
  {
    esg_id: 3671,
    company_name: 'IHS Markit Ltd.',
    exchange_symbol: 'NYSE',
    stock_symbol: 'INFO',
    environment_grade: 'AA',
    environment_level: 'Excellent',
    social_grade: 'BB',
    social_level: 'Medium',
    governance_grade: 'BB',
    governance_level: 'Medium',
    total_grade: 'A',
    total_level: 'High',
    disclaimer:
      'ESG Enterprise\'s ESG Rating data ("Scores") are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '13-03-2022',
    environment_score: 613,
    social_score: 309,
    governance_score: 345,
    total: 1267,
  },
  {
    esg_id: 6733,
    company_name: 'STMicroelectronics N.V.',
    exchange_symbol: 'XPAR',
    stock_symbol: 'STM',
    environment_grade: 'A',
    environment_level: 'High',
    social_grade: 'BB',
    social_level: 'Medium',
    governance_grade: 'BB',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'High',
    disclaimer:
      'ESG Enterprise\'s ESG Rating data ("Scores") are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '14-03-2022',
    environment_score: 500,
    social_score: 341,
    governance_score: 300,
    total: 1141,
  },
  {
    esg_id: 5244,
    company_name: 'NVIDIA Corporation',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'NVDA',
    environment_grade: 'BB',
    environment_level: 'Medium',
    social_grade: 'BB',
    social_level: 'Medium',
    governance_grade: 'B',
    governance_level: 'Medium',
    total_grade: 'BB',
    total_level: 'Medium',
    disclaimer:
      'ESG Enterprise\'s ESG Rating data ("Scores") are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '14-03-2022',
    environment_score: 323,
    social_score: 321,
    governance_score: 275,
    total: 919,
  },
  {
    esg_id: 6163,
    company_name: 'Rogers Corporation',
    exchange_symbol: 'NYSE',
    stock_symbol: 'ROG',
    environment_grade: 'A',
    environment_level: 'High',
    social_grade: 'BBB',
    social_level: 'High',
    governance_grade: 'BB',
    governance_level: 'Medium',
    total_grade: 'A',
    total_level: 'High',
    disclaimer:
      'ESG Enterprise\'s ESG Rating data ("Scores") are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '14-03-2022',
    environment_score: 525,
    social_score: 407,
    governance_score: 300,
    total: 1232,
  },
  {
    esg_id: 5341,
    company_name: 'Oracle Corporation',
    exchange_symbol: 'NYSE',
    stock_symbol: 'ORCL',
    environment_grade: 'A',
    environment_level: 'High',
    social_grade: 'BB',
    social_level: 'Medium',
    governance_grade: 'BB',
    governance_level: 'Medium',
    total_grade: 'A',
    total_level: 'High',
    disclaimer:
      'ESG Enterprise\'s ESG Rating data ("Scores") are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '14-03-2022',
    environment_score: 540,
    social_score: 325,
    governance_score: 360,
    total: 1225,
  },
  {
    esg_id: 4847,
    company_name: 'Motorola Solutions, Inc.',
    exchange_symbol: 'NYSE',
    stock_symbol: 'MSI',
    environment_grade: 'A',
    environment_level: 'High',
    social_grade: 'BB',
    social_level: 'Medium',
    governance_grade: 'BB',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'High',
    disclaimer:
      'ESG Enterprise\'s ESG Rating data ("Scores") are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '13-03-2022',
    environment_score: 505,
    social_score: 305,
    governance_score: 352,
    total: 1162,
  },
  {
    esg_id: 5909,
    company_name: 'QUALCOMM Incorporated',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'QCOM',
    environment_grade: 'BBB',
    environment_level: 'High',
    social_grade: 'BB',
    social_level: 'Medium',
    governance_grade: 'BB',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'High',
    disclaimer:
      'ESG Enterprise\'s ESG Rating data ("Scores") are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '14-03-2022',
    environment_score: 409,
    social_score: 300,
    governance_score: 300,
    total: 1009,
  },
  {
    esg_id: 6411,
    company_name: 'The Sherwin-Williams Company',
    exchange_symbol: 'NYSE',
    stock_symbol: 'SHW',
    environment_grade: 'BBB',
    environment_level: 'High',
    social_grade: 'B',
    social_level: 'Medium',
    governance_grade: 'B',
    governance_level: 'Medium',
    total_grade: 'BB',
    total_level: 'Medium',
    disclaimer:
      'ESG Enterprise\'s ESG Rating data ("Scores") are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '14-03-2022',
    environment_score: 405,
    social_score: 289,
    governance_score: 250,
    total: 944,
  },
  {
    esg_id: 6930,
    company_name: 'TE Connectivity Ltd.',
    exchange_symbol: 'NYSE',
    stock_symbol: 'TEL',
    environment_grade: 'B',
    environment_level: 'Medium',
    social_grade: 'B',
    social_level: 'Medium',
    governance_grade: 'B',
    governance_level: 'Medium',
    total_grade: 'B',
    total_level: 'Medium',
    disclaimer:
      'ESG Enterprise\'s ESG Rating data ("Scores") are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '14-03-2022',
    environment_score: 200,
    social_score: 200,
    governance_score: 200,
    total: 600,
  },
  {
    esg_id: 3485,
    company_name: 'Hewlett Packard Enterprise Company',
    exchange_symbol: 'NYSE',
    stock_symbol: 'HPE',
    environment_grade: 'B',
    environment_level: 'Medium',
    social_grade: 'BB',
    social_level: 'Medium',
    governance_grade: 'B',
    governance_level: 'Medium',
    total_grade: 'BB',
    total_level: 'Medium',
    disclaimer:
      'ESG Enterprise\'s ESG Rating data ("Scores") are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '13-03-2022',
    environment_score: 248,
    social_score: 325,
    governance_score: 235,
    total: 808,
  },
  {
    esg_id: 2647,
    company_name: 'Exponent, Inc.',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'EXPO',
    environment_grade: 'A',
    environment_level: 'High',
    social_grade: 'BB',
    social_level: 'Medium',
    governance_grade: 'BB',
    governance_level: 'Medium',
    total_grade: 'A',
    total_level: 'High',
    disclaimer:
      'ESG Enterprise\'s ESG Rating data ("Scores") are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '12-03-2022',
    environment_score: 580,
    social_score: 301,
    governance_score: 340,
    total: 1221,
  },
  {
    esg_id: 121,
    company_name: 'Adobe Inc.',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'ADBE',
    environment_grade: 'B',
    environment_level: 'Medium',
    social_grade: 'B',
    social_level: 'Medium',
    governance_grade: 'B',
    governance_level: 'Medium',
    total_grade: 'B',
    total_level: 'Medium',
    disclaimer:
      'ESG Enterprise\'s ESG Rating data ("Scores") are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '11-03-2022',
    environment_score: 255,
    social_score: 212,
    governance_score: 255,
    total: 722,
  },
  {
    esg_id: 3485,
    company_name: 'Hewlett Packard Enterprise Company',
    exchange_symbol: 'NYSE',
    stock_symbol: 'HPE',
    environment_grade: 'B',
    environment_level: 'Medium',
    social_grade: 'BB',
    social_level: 'Medium',
    governance_grade: 'B',
    governance_level: 'Medium',
    total_grade: 'BB',
    total_level: 'Medium',
    disclaimer:
      'ESG Enterprise\'s ESG Rating data ("Scores") are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '13-03-2022',
    environment_score: 248,
    social_score: 325,
    governance_score: 235,
    total: 808,
  },
  {
    esg_id: 2647,
    company_name: 'Exponent, Inc.',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'EXPO',
    environment_grade: 'A',
    environment_level: 'High',
    social_grade: 'BB',
    social_level: 'Medium',
    governance_grade: 'BB',
    governance_level: 'Medium',
    total_grade: 'A',
    total_level: 'High',
    disclaimer:
      'ESG Enterprise\'s ESG Rating data ("Scores") are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '12-03-2022',
    environment_score: 580,
    social_score: 301,
    governance_score: 340,
    total: 1221,
  },
  {
    esg_id: 121,
    company_name: 'Adobe Inc.',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'ADBE',
    environment_grade: 'B',
    environment_level: 'Medium',
    social_grade: 'B',
    social_level: 'Medium',
    governance_grade: 'B',
    governance_level: 'Medium',
    total_grade: 'B',
    total_level: 'Medium',
    disclaimer:
      'ESG Enterprise\'s ESG Rating data ("Scores") are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '11-03-2022',
    environment_score: 255,
    social_score: 212,
    governance_score: 255,
    total: 722,
  },
  {
    esg_id: 4557,
    company_name: 'Matson, Inc.',
    exchange_symbol: 'NYSE',
    stock_symbol: 'MATX',
    environment_grade: 'A',
    environment_level: 'High',
    social_grade: 'BB',
    social_level: 'Medium',
    governance_grade: 'BB',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'High',
    disclaimer:
      'ESG Enterprise\'s ESG Rating data ("Scores") are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '13-03-2022',
    environment_score: 533,
    social_score: 320,
    governance_score: 300,
    total: 1153,
  },
  {
    esg_id: 74042,
    company_name: 'Stellantis N.V.',
    exchange_symbol: 'NYSE',
    stock_symbol: 'STLA',
    environment_grade: 'A',
    environment_level: 'High',
    social_grade: 'BB',
    social_level: 'Medium',
    governance_grade: 'BB',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'High',
    disclaimer:
      'ESG Enterprise\'s ESG Rating data ("Scores") are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '14-02-2022',
    environment_score: 505,
    social_score: 340,
    governance_score: 315,
    total: 1160,
  },
  {
    esg_id: 1982,
    company_name: 'Crown Holdings, Inc.',
    exchange_symbol: 'NYSE',
    stock_symbol: 'CCK',
    environment_grade: 'A',
    environment_level: 'High',
    social_grade: 'A',
    social_level: 'High',
    governance_grade: 'BB',
    governance_level: 'Medium',
    total_grade: 'A',
    total_level: 'High',
    disclaimer:
      'ESG Enterprise\'s ESG Rating data ("Scores") are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '12-03-2022',
    environment_score: 555,
    social_score: 501,
    governance_score: 305,
    total: 1361,
  },
];

const esgCompanies = data.map((entry) => {
  const company = {};
  company.ticker = entry.stock_symbol;
  company.environmentScore = entry.environment_score;
  company.socialScore = entry.social_score;
  company.governanceScore = entry.governance_score;
  return company;
});

console.log(esgCompanies);
